2019-03-07 15:59:58,186-DEBUG-my_log.py-python14-日志信息:这是一个debug信息
2019-03-07 15:59:58,187-INFO-my_log.py-python14-日志信息:这是一个info信息
2019-03-07 15:59:58,187-WARNING-my_log.py-python14-日志信息:这是一个warning信息
2019-03-07 15:59:58,187-ERROR-my_log.py-python14-日志信息:这是一个error信息
2019-03-07 15:59:58,188-CRITICAL-my_log.py-python14-日志信息:这是一个critical信息
2019-03-07 16:02:41,984-DEBUG-[my_log.py]-python14-[日志信息]:这是一个debug信息
2019-03-07 16:02:41,984-INFO-[my_log.py]-python14-[日志信息]:这是一个info信息
2019-03-07 16:02:41,984-WARNING-[my_log.py]-python14-[日志信息]:这是一个warning信息
2019-03-07 16:02:41,984-ERROR-[my_log.py]-python14-[日志信息]:这是一个error信息
2019-03-07 16:02:41,985-CRITICAL-[my_log.py]-python14-[日志信息]:这是一个critical信息
2019-03-07 16:28:31,213-INFO-my_log.py-python14-日志信息:这是一条debug信息！
2019-03-07 16:31:47,034-INFO-my_log.py-python14-日志信息:这是一条info信息！
2019-03-07 17:31:20,813-INFO-33-my_log.py-python14-日志信息:这是一条info信息！
2019-03-07 17:35:33,371-INFO-33-my_log.py-python14-日志信息:这是一条info信息！
2019-03-07 17:35:40,952-INFO-33-my_log.py-python14-日志信息:这是一条info信息！
2019-03-07 17:56:08,203-INFO-32-my_log.py-python14-日志信息:msg
2019-03-07 17:56:17,140-ERROR-36-my_log.py-python14-日志信息:msg
2019-03-07 17:56:44,033-ERROR-36-my_log.py-python14-日志信息:msg
2019-03-07 17:56:44,039-INFO-32-my_log.py-python14-日志信息:msg
2019-03-07 17:58:49,872-INFO-32-my_log.py-python14-日志信息:msg
2019-03-07 17:59:28,113-ERROR-36-my_log.py-python14-日志信息:msg
2019-03-07 17:59:28,118-INFO-32-my_log.py-python14-日志信息:msg
2019-03-07 17:59:33,778-ERROR-36-my_log.py-python14-日志信息:msg
2019-03-07 17:59:33,783-INFO-32-my_log.py-python14-日志信息:msg
2019-03-07 17:59:47,479-ERROR-36-my_log.py-python14-日志信息:这是一条error信息！
2019-03-07 17:59:47,484-INFO-32-my_log.py-python14-日志信息:这是一条info信息！
2019-03-07 18:00:09,211-INFO-32-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:01:10,306-ERROR-[36]-my_log.py-python14-日志信息:这是一条error信息！
2019-03-07 18:01:10,311-INFO-[32]-my_log.py-python14-日志信息:这是一条info信息！
2019-03-07 18:01:33,233-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:01:44,688-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:04:56,248-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:04:56,253-INFO-[32]-my_log.py-python14-日志信息:数据读入完毕！
2019-03-07 18:08:31,654-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:08:31,661-INFO-[32]-my_log.py-python14-日志信息:数据读入完毕！
2019-03-07 18:08:37,447-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:08:37,451-INFO-[32]-my_log.py-python14-日志信息:数据读入完毕！
2019-03-07 18:09:16,491-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:09:16,496-INFO-[32]-my_log.py-python14-日志信息:数据读入完毕！
2019-03-07 18:11:04,363-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:11:04,368-INFO-[32]-my_log.py-python14-日志信息:数据读入完毕！
2019-03-07 18:11:04,404-INFO-[32]-my_log.py-python14-日志信息:开始写入数据了！
2019-03-07 18:11:04,437-INFO-[32]-my_log.py-python14-日志信息:数据写入完毕！
2019-03-07 18:11:21,681-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:11:21,685-INFO-[32]-my_log.py-python14-日志信息:数据读入完毕！
2019-03-07 18:11:21,718-INFO-[32]-my_log.py-python14-日志信息:开始写入数据了！
2019-03-07 18:11:21,747-INFO-[32]-my_log.py-python14-日志信息:数据写入完毕！
2019-03-07 18:11:28,097-INFO-[32]-my_log.py-python14-日志信息:开始读取测试数据了！
2019-03-07 18:11:28,102-INFO-[32]-my_log.py-python14-日志信息:数据读入完毕！
2019-03-07 18:11:28,135-INFO-[32]-my_log.py-python14-日志信息:开始写入数据了！
2019-03-07 18:11:28,164-INFO-[32]-my_log.py-python14-日志信息:数据写入完毕！
2019-03-07 19:05:42,706-ERROR-[36]-my_log.py-python14-日志信息:3 != 4
2019-03-07 19:06:42,234-ERROR-[36]-my_log.py-python14-日志信息:3 != 4
2019-03-07 19:07:13,239-ERROR-[36]-my_log.py-python14-日志信息:3 != 4
2019-03-07 19:07:50,695-ERROR-[36]-my_log.py-python14-日志信息:3 != 4
2019-03-07 19:28:34,815-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:28:34,820-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:29:36,716-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:29:36,722-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:30:06,598-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:30:06,603-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:30:14,726-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:30:14,731-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:33:13,062-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:33:13,069-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:35:16,943-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:35:16,948-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:35:58,001-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:35:58,005-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:35:58,010-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:35:58,014-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:36:26,791-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:36:26,796-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-07 19:36:35,721-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-07 19:36:35,725-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-12 15:45:43,857-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-12 17:14:38,475-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-14 14:36:02,142-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-14 14:36:02,150-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
2019-03-14 14:36:25,504-ERROR-[36]-my_log.py-python14-日志信息:1 != -3
2019-03-14 14:36:25,509-ERROR-[36]-my_log.py-python14-日志信息:-1 != 3
